### ISSUE TITLE
Problem in output

### ISSUE THREAD

**Issue by ahsan3803** [lixiny/bihand#1]
I'm getting wrong output results on both datasets using pre-trained weights. Below is my output. 

on RHD datasets
![RHD](https://user-images.githubusercontent.com/58796370/93875979-9b94b000-fd08-11ea-9464-94f410a66f6e.png)

and on STB datasets
![STB](https://user-images.githubusercontent.com/58796370/93876026-b23b0700-fd08-11ea-9b7b-202334d53742.png)

How to solve this problem?

**Comment by lixiny** [comment]
Could you show me the terminal outputs when the problem occurs. 

Lixin

**Comment by ahsan3803** [comment]
@lixiny  here is screenshot of output

![terminal_output](https://user-images.githubusercontent.com/58796370/93878780-355e5c00-fd0d-11ea-9e37-25aef496950c.png)

**Comment by lixiny** [comment]
@ahsan3803 The first guess is that you didn't load the pre-trained models correctly. 
bihand `run.py` won't crash, instead, it will initialize the networks with random weights. 

if your config is correct. 
the output should like this: 

![image](https://user-images.githubusercontent.com/32672902/93879038-9e45d400-fd0d-11ea-8a36-6728a093363e.png)

**Comment by ahsan3803** [comment]
Thanks @lixiny  I have solved it. checkpoints path was wrong.
