### ISSUE TITLE
SIK dataset

### ISSUE THREAD

**Issue by llpspark** [lixiny/bihand#10]
hi， nice work for hand 3D. I wonder to know what's the relationship between SIK-1M and SIK-fh dataset, I just found SIK-fh have some large range pose compare to SIK-1M.

**Comment by lixiny** [comment]
Thanks for you interest in our work ! If i remember correctly, the SIK-fh is the joint rotation-location pairs of the samples in freiHAND (''-fh'') dataset !

**Comment by llpspark** [comment]
thank u for ur reply @lixiny @LyuJ1998 . and I wonder to know how to get  the pose parameter(quat) ? generally,  I think  it maybe come from  48 dimensional (the first 3 dim is global rotation parameters) MANO pose vector in axis-angle representation minus the mean pose, and then convert to Quaternion represention,  it just like the InterHand MANO annot: https://mks0601.github.io/InterHand2.6M/ , Is that right?

**Comment by lixiny** [comment]
> sional (the first 3 dim is global rotation parameters) MANO pose vector in axis-angle representation minus the mean pose, and then convert to Quat

Not necessarily need to minus the mean pose. It depends how the original MANO params are obtained.
