### ISSUE TITLE
关于uvd坐标的处理

### ISSUE THREAD

**Issue by liuyamjune** [lixiny/bihand#18]
您好，请问是否对关节点的uvd坐标进行归一化标准化的处理？

**Comment by lixiny** [comment]
是做了归一化处理的。请看[这里](https://github.com/lixiny/bihand/blob/f9bab9c75d13cd0f61c90638a4fc035685ad3797/bihand/utils/handutils.py#L54);

**Comment by liuyamjune** [comment]
非常感谢您的解答。但是在训练的时候仍然存在一些疑问，我在复现的时候，将得到的3D坐标和真实3D坐标都转化为毫米单位（*1000.0），计算得到的loss值显示达到几千（loss值并在不断降低），评价指标还是在正常范围，这样的loss也算正常的吗？

期待您的回复。

**Comment by lixiny** [comment]
光看loss 的数值很难说，具体可以试一下将3D结果plot出来看看, 比如，将预测的3Djoints/mesh通过内参投影到2D图像。

**Comment by liuyamjune** [comment]
感谢您的解答。

**Comment by YimjuneLiu** [comment]
> 光看loss 的数值很难说，具体可以试一下将3D结果plot出来看看, 比如，将预测的3Djoints/mesh通过内参投影到2D图像。

如果我是通过热图计算得到坐标，然后再通过网络提升到3d，这样得到的坐标可以用您代码中的uvd2xyz函数进行坐标转换吗？
