### ISSUE TITLE
about liftnet , I have a question

### ISSUE THREAD

**Issue by Liangdacai** [lixiny/bihand#2]
hi~
In the liftnet part, why use "joint_root" and "joint_bone" as a prior information? I use a normal camera to get the RGB image, without "joint_root" and "joint_bone" . How to obtain "joint_root" and "joint_bone" ?   Thanks

**Comment by lixiny** [comment]
Yes, we currently use the **_joint root depth_** and **_reference hand MCP bone length_** as a prior information.  The code is meant to reproduce the results reported in paper, which is, however, cannot be applied directly in the wild. 
You could create a synthetic dataset and train a neural network to predict the root joint depth and bone scale in your application. 

lixin
