### ISSUE TITLE
about Inverse Kinematics Dataset

### ISSUE THREAD

**Issue by MengHao666** [lixiny/bihand#4]
Hi, I am curious about the generation of Inverse Kinematics Dataset.

In your paper, u randomly sample 20k pose and shape parameters with normal distribution.
However, could it ensure all the pose and shape params valid physically, especially no interpolation between each finger?
What do u make of all this?

Thanks,
Hao

**Comment by lixiny** [comment]
Hi, Hao
Indeed, randomly sampled pose and shape parameters cannot guarantee the valid hand configuration.

The core function of the large-scale IKDataset is to enable the SIKNet to solve the general hand IK problem (position -> rotation). Therefore, when transferring SIKNet into real hand pose estimation, we need to fine-tune the SIKNet on dataset with *valid* hand (STB, RHD) for a number of iterations. eg. `python training/train_siknet.py --fine_tune stb ##(or rhd)`

Hope this can help you. 
Lixin

**Comment by MengHao666** [comment]
> Hi, Hao
> Indeed, randomly sampled pose and shape parameters cannot guarantee the valid hand configuration.
> 
> The core function of the large-scale IKDataset is to enable the SIKNet to solve the general hand IK problem (position -> rotation). Therefore, when transferring SIKNet into real hand pose estimation, we need to fine-tune the SIKNet on dataset with _valid_ hand (STB, RHD) for a number of iterations. eg. `python training/train_siknet.py --fine_tune stb ##(or rhd)`
> 
> Hope this can help you.
> Lixin

Thanks!
