### ISSUE TITLE
3D feature map‘s contribution

### ISSUE THREAD

**Issue by yunshangyue71** [lixiny/bihand#5]
hi, i have several questions about this project. 1、LiftNet predict 3d heatmap, why not only predict depth?the uv can get from 2D headmap.2、if can predict only depth ， how about cut the H3d and gain the depth net’s resolution.
thank you very much

**Comment by lixiny** [comment]
Indeed, only depth is demanded in 3DHeatmap, the **UV** in UVD map is more likely to be an auxiliary.  Thanks for providing a new heuristic.
