### ISSUE TITLE
download STB dataset

### ISSUE THREAD

**Issue by 109318401ntut** [lixiny/bihand#7]
Hello ,
When I downloaded STBdataset, I found that there are two files, one is the image and the other is the label. According to your readme, the image file must have
                 SK_color_0.png
                 SK_depth_0.png
                 SK_depth_seg_0.png
But I only see SK_depth_seg_0.png, is there any other link for download stb dataset ? 
thank for your help~
![image](https://user-images.githubusercontent.com/75209634/122877025-ba43d800-d368-11eb-8c2c-7c3608b47d03.png)

**Comment by lixiny** [comment]
Hi, we only provide the **STB_supp** datasets that contains the `SK_depth_seg_${number}.png`.
The **STB_supp** should be merged into the **STB official dataset** ([download link](https://sites.google.com/site/zhjw1988/))

**Comment by 109318401ntut** [comment]
ok,thank you!
