### ISSUE TITLE
How to get 3D coordinates of camera coordinate system？

### ISSUE THREAD

**Issue by youngstu** [lixiny/bihand#8]
How to get 3D coordinates of camera coordinate system instead of MANO space？

Considering that the absolute coordinates of hand are not obtained, how can 3d hand tracking be applied to augmented reality scenes such as AR glasses?

**Comment by youngstu** [comment]
Using 3D joint and human-computer interaction control, such as Nreal AR glasses.

https://www.youtube.com/watch?v=9LxOlsHu3r8&ab_channel=UploadVR

If there is no absolute depth, it is impossible to judge whether the button has been touched.

**Comment by lixiny** [comment]
Two other ways to get the absolute coordinates (aka. coordinates in camera space) of hand's root.

1)  Train a root recovery module (eg. RootNet [[1]](https://openaccess.thecvf.com/content_ICCV_2019/html/Moon_Camera_Distance-Aware_Top-Down_Approach_for_3D_Multi-Person_Pose_Estimation_From_ICCV_2019_paper.html) and Global Mesh Registration [[2]](https://openaccess.thecvf.com/content/CVPR2021/html/Chen_Camera-Space_Hand_Mesh_Recovery_via_Semantic_Aggregation_and_Adaptive_2D-1D_CVPR_2021_paper.html)
2)  Solve the root coordinates by eq. (5) in [[3]](https://openaccess.thecvf.com/content_CVPR_2020/html/Zhou_Monocular_Real-Time_Hand_Shape_and_Motion_Capture_Using_Multi-Modal_Data_CVPR_2020_paper.html)

Hope these can help you. 
Best
