### ISSUE TITLE
train_seednet problem

### ISSUE THREAD

**Issue by 109318401ntut** [lixiny/bihand#9]
I'm runed the train_seednet.py ,it showed some error
![image](https://user-images.githubusercontent.com/75209634/125883696-3d868cf0-6a8d-4b16-ba8c-ee6a4442d9df.png)
![image](https://user-images.githubusercontent.com/75209634/125883757-0d8bdc14-0a9e-4490-91ec-ae27cdaff89d.png)
it shows 'FileNotFoundError: [Errno 2] No such file or directory: 'data\\RHD_published_v2\\training\\color\\34356.png'' 
and 'FileNotFoundError: [Errno 2] No such file or directory: 'data\\RHD_published_v2\\training\\color\\31263.png''.
but I check my folder that has two images. 
![image](https://user-images.githubusercontent.com/75209634/125884262-12075159-ec4f-4221-8a90-06d7829eb6a4.png)
![image](https://user-images.githubusercontent.com/75209634/125884374-1c416045-00b5-48b2-b638-7fd621b88be8.png)
Could you  advise me?  thank you!

**Comment by lixiny** [comment]
Hi,
Thanks for your interest and your message.
This `bihand` repo were developed on Linux (Ubuntu 18.04) OS so change to other OS may causes unexpected bugs.
From my inspection, the `rhd\\RHD_published_v2\\` path identifier usually comes from Windows OS. 
I suggest you check all the path identifiers before starting development.

Besides,  the image may have been broken. Check them too. 

Best, 
Lixin

**Comment by 109318401ntut** [comment]
ok,Thanks for your help.
